Add controllers
valentin32k/java-shareit pull request #1
Opened 2023-04-14 23:20 UTC by valentin32k

2023-04-15 11:08 UTC, Donald522 requested changes
Привет!

Оставил несколько замечаний

2023-04-15 11:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return itemsById.values()
Тут можно было сделать вторую мапу ownerId <-> Item, чтобы имитировать индекс

2023-04-15 11:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (text.equals("")) {
Тут nullpointer будет
Сравнение строки с константой пишут наоборот: `"".equals(text)`
Либо `StringUtils.isBlank(text)`

2023-04-15 11:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getOwner().getId() != currentItem.getOwner().getId()) {
Тут тоже nullpointer будет, если по id не найдется ничего в storage

2023-04-16 10:25 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    long id = 0;
Исправил

2023-04-16 10:32 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (text.equals("")) {
Второй раз на те же грабли. Прошу прощения. Все исправил

2023-04-16 10:44 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getOwner().getId() != currentItem.getOwner().getId()) {
По идее не должен. У меня в методе getItemById проверка на null и NotFoundException.

2023-04-16 17:43 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/exceptions/ExceptionHandlers.java
> +    public ResponseEntity<Map<String, String>> badUserException(final ValidationException e) {
Поправил

2023-04-16 17:52 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return itemsById.values()
Честно говоря, не понял замысла. Можно немного подробней? В следующей итерации обязательно все поправлю

2023-04-16 17:56 UTC, valentin32k commented
Привет!
Спасибо за ревью. 
Не исправленными остались два замечания - вопросы в комментариях к ним

2023-04-16 19:30 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getOwner().getId() != currentItem.getOwner().getId()) {
А, не заметил, что тут приватный метод вызывается.

2023-04-16 19:37 UTC, Donald522 approved these changes
Привет!

Про npe - ты прав, я не обратил внимание, что приватный метод используется. Извиняюсь.

Про запрос getByOwnerId написал подробнее, но сильно останавливаться на этом не будем, все равно дальше будет база.

2023-04-16 19:37 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return itemsById.values()
Это не критичный момент.

Сложность этого метода O(кол-во вещей сохраненных)

Когда видишь название метода get<что-то по id> ожидаешь, что это будет работать за O(1)
Поэтому тут можно было бы иметь еще одну Map: ownerId <-> List<Item> (в первом комментарии я List не написал). В таком случае получение списка вещей пользователя будет работать за константное время. При этом мы немного проиграем на сохранении, но во-первых не сильно, а во-вторых этим можно пожертвовать ради быстрого чтения.

В БД мы бы сделали просто индекс по полю ownerId в таблице item

2023-04-30 16:03 UTC, merged