Add item requests
valentin32k/java-shareit pull request #3
Opened 2023-05-27 22:00 UTC by valentin32k

2023-05-28 14:30 UTC, Donald522 requested changes
Привет!

Все хорошо, я бы предложил доставать запрос с вещами одним запросом

2023-05-28 14:30 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/dto/InputCommentDto.java
> +@Getter
Вроде бы это все можно заменить аннотацией Data

2023-05-30 18:35 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/item/dto/InputCommentDto.java
> +@Getter
Заменил

2023-05-30 18:36 UTC, valentin32k commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        addItemsToItemsRequests(itemRequests);
Такой запрос составить не получилось. Прошу помочь

2023-05-30 19:12 UTC, merged