feat: add docker and gateway
valentin32k/java-shareit pull request #4
Opened 2023-06-07 22:37 UTC by valentin32k

2023-06-09 18:55 UTC, Donald522 requested changes
Привет!
Все хорошо, но пару минорных комментов все же оставил

2023-06-09 18:55 UTC, Donald522 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
А почему не 14?

2023-06-09 18:55 UTC, Donald522 commented on docker-compose.yml
> +      - POSTGRES_USER=root
Под root-ом не очень ходить в базу как-то

2023-06-09 18:55 UTC, Donald522 commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +    // Все
В чем смысл таких комментариев?)
Код должен быть самодокументированным. Твои названия enum-ов хорошо говорят сами за себя, нет смысла замусоривать код комментариями

2023-06-09 18:55 UTC, Donald522 commented on server/pom.xml
> +        <dependency>
А это что и зачем?

2023-06-09 19:36 UTC, valentin32k commented on docker-compose.yml
> +    image: postgres:13.7-alpine
Исправил

2023-06-09 19:36 UTC, valentin32k commented on docker-compose.yml
> +      - POSTGRES_USER=root
Исправил

2023-06-09 19:37 UTC, valentin32k commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +    // Все
Смысла нет, комментариев теперь тоже нет)

2023-06-09 19:49 UTC, valentin32k commented on server/pom.xml
> +        <dependency>
Это здесь точно лишнее. Убрал

2023-06-10 10:07 UTC, Donald522 approved these changes

2023-06-10 10:07 UTC, Donald522 commented on docker-compose.yml
> +      - POSTGRES_USER=user
Вообще советую давать пользователям имя, совпадающее с именем сервиса. Это упростит жизнь в моменты, когда надо будет смотреть кто нагружает БД, например.

2023-06-13 19:26 UTC, merged